version: '2.4'

x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: root # ${USERNAME}
  SPRING_DATASOURCE_PASSWORD: root # ${PASSWORD}

services:
  db:
    image: mysql
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - 3306:3306
    volumes:
      - devdojo_data:/var/lib/mysql
    mem_limit: 512m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml" # mapping the prometheus config created to the container
    command: "--config.file=/etc/prometheus/prometheus.yml" # when the container is created, run this command setting up the config file mapped above
    ports:
      - 9090:9090
    mem_limit: 128m

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    mem_limit: 128m

  springboot2-essentials:
    image: psatler/springboot2-essentials:0.0.1-SNAPSHOT
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      <<: *database-variables # inserting all the env vars defined above
    mem_limit: 512m

volumes:
  devdojo_data: