version: '3.2'
services:
  db:
    image: mysql
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - 3306:3306
    volumes:
      - devdojo_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml" # mapping the prometheus config created to the container
    command: # when the container is created, run this command setting up the config file mapped above
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000

volumes:
  devdojo_data: