
server:
  error:
    include-stacktrace: on-param # hiding the errors on return. Only show if we set param as ?trace=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
  # every time we start our application, our database gets updated by the command below
    hibernate:
      ddl-auto: update
    # show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2 Essetials
  website: https://devdojo.academy/
  github: https://github.com/psatler/spring-boot-essentials
